# Generated by Django 4.2.7 on 2026-02-04 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_equipmentorder_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('A', 'Grade A - Premium Quality'), ('B', 'Grade B - Good Quality'), ('C', 'Grade C - Standard Quality'), ('D', 'Grade D - Basic Quality')], max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity in kg')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop for Sale',
                'verbose_name_plural': 'Crops for Sale',
                'ordering': ['-created_at'],
            },
        ),
    ]
