# Generated by Django 4.2.7 on 2026-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_course_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='availability_status',
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity_available',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_rent', 'On Rent')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
